version: "3"

services:
  client:
    build: ./client
    ports:
      - 8080:8080
    volumes:
      - ./:/client
      - /client/node_modules
    environment:
      - API_URL=http://localhost:5000/

  server:
    build: ./server
    ports:
      - 5000:5000
    volumes:
      - ./:/server
      - /servr/node_modules
    depends_on: 
      - server-database
    environment:
      - DATABASE_URL=server-database:27017
    
  server-database:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
