version: "3"

services:
  client:
    build: ./client
    ports:
      - 8081:8081
    volumes:
      - ./client:/data
    environment:
      - API_URL=http://localhost:5000/

  server:
    build: ./server
    ports:
      - 5000:5000
    volumes:
      - ./server:/app
    depends_on: 
      - server-database
    links:
      - server-database
    
  server-database:
    image: mongo
    ports:
      - 27017:27017