version: "3"

services:
  client:
    build: ./client
    ports:
      - 8080:8080
    volumes:
      - ./client:/data
    environment:
      - API_URL=http://localhost:5000/

  server:
    build: ./server
    ports:
      - 5000:5000
    volumes:
      - ./server:/data
    depends_on: 
      - server-database
    environment:
      - DATABASE_URL=server-database:27017
    
  server-database:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
